name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      - name: yarn install and build
        env:
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        run:
          yarn install
          # This triggers `gatsby build` script in "package.json"
          yarn run build
          # 4. Deploy the gatsby build to Netlify
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avzh --delete "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/* ${remote_user}@${remote_host}:/var/www/stratogram.ca/html"
