name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: yarn install
      # This triggers `gatsby build` script in "package.json"
      - run: yarn run build
      # 4. Deploy the gatsby build to Netlify
      