name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      #- name: Install Dependencies
      #  run: yarn install
      #- name: Build
      #  run: yarn run build
      - name: Echo key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzh --delete
          path: public/
          remote_path: /var/www/stratogram.ca/html
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          