name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Make dir
        run: mkdir -p ~/.ssh
      - name: SSH Add
        env:
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh-add <(echo ${remote_key} | base64 --decode)
      - name: Secure dir
        run: | 
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
      - name: Keyscan
        env:
          remote_host: ${{ secrets.SERVER_IP }}
        run: ssh-keyscan ${remote_host} >> ~/.ssh/known_hosts
      - name: Secure file
        run: chmod 644 ~/.ssh/known_hosts
      - name: Deploy to server
        env:
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
        run: rsync -avzh --delete public/* ${remote_user}@${remote_host}:/var/www/stratogram.ca/html
  
