name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy
        env:
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avzh --delete "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/* ${remote_user}@${remote_host}:/var/www/stratogram.ca/html
