name: Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - release

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      #- name: Install Dependencies
      #  run: yarn install
      #- name: Build
      #  run: yarn run build
      - name: Echo key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode
      - name: Make dir
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
      - name: Keyscan file
        run: | 
          ssh-keyscan "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Send files to server
        env:
          remote_user: ${{ secrets.SERVER_USER }}
          remote_host: ${{ secrets.SERVER_IP }}
        run: rsync -avzh --delete -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/* ${remote_user}@${remote_host}:/var/www/stratogram.ca/html
